name: Daily Data Fetch and Release

on:
  schedule:
    # Runs at 01:00 UTC daily. Adjust as needed.
    # Recommendation: Choose a time with generally low activity for your APIs.
    - cron: '0 1 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  fetch-and-release-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed by softprops/action-gh-release to create releases/tags
      # Other permissions might be needed if your etudes access private resources via tokens

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # If you want to commit back to the repo (alternative to releases), you'd need:
        # with:
        #   token: ${{ secrets.YOUR_PAT_IF_NEEDED }} # A PAT if GITHUB_TOKEN doesn't have push rights to protected main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Or your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          else echo "requirements.txt not found, skipping pip install -r."
          fi

      - name: Run daily data fetching tasks
        id: daily_run
        run: |
          echo "Running trouble daily script..."
          # Execute the script and capture its JSON output.
          # The script prints JSON between specific markers.
          OUTPUT_JSON=$(python -m trouble daily)

          # Extract JSON content between markers
          # This assumes your script prints "--- Daily Tasks Output JSON Start ---"
          # and "--- Daily Tasks Output JSON End ---" around the JSON block.
          JSON_CONTENT=$(echo "$OUTPUT_JSON" | awk '/--- Daily Tasks Output JSON Start ---/{flag=1; next} /--- Daily Tasks Output JSON End ---/{flag=0} flag')

          if [ -z "$JSON_CONTENT" ]; then
            echo "::error::Failed to extract JSON content from daily script output."
            echo "Full output was:"
            echo "$OUTPUT_JSON"
            exit 1
          fi

          # Validate JSON (optional but good practice)
          echo "$JSON_CONTENT" | python -m json.tool > /dev/null
          if [ $? -ne 0 ]; then
            echo "::error::Extracted content is not valid JSON."
            echo "Extracted content was:"
            echo "$JSON_CONTENT"
            exit 1
          fi

          echo "Successfully extracted JSON content."
          # Save the extracted JSON to a file for upload
          echo "$JSON_CONTENT" > daily_etude_data.json
          echo "Saved data to daily_etude_data.json"
          cat daily_etude_data.json # Print file content to logs for verification

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Default, usually sufficient
        with:
          tag_name: data-${{ env.RELEASE_DATE }} # Date-based tag
          name: "Daily Etude Data - ${{ env.RELEASE_DATE }}"
          body: |
            Automated daily data release for etudes.
            Date: ${{ env.RELEASE_DATE }}
            Contains `daily_etude_data.json` with fetched content.
          draft: false
          prerelease: false
          files: daily_etude_data.json # The file generated by the previous step
        env:
          RELEASE_DATE: $(date +'%Y-%m-%d') # Set current date for tag/name

      # Optional: Cleanup old releases (more complex, consider for later)
      # - name: Cleanup Old Data Releases
      #   if: success() # Only run if release succeeded
      #   uses: ... some action or script to list and delete old releases ...
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     days_to_keep: 7 # Or number of releases to keep

      - name: Echo success message
        run: echo "Daily data fetch and release process completed successfully."

# Notes for user:
# 1. GITHUB_TOKEN: The default GITHUB_TOKEN has permissions to create releases in the same repository.
#    If you encounter permission issues, you might need a Personal Access Token (PAT) with `repo` or `public_repo` scope,
#    stored as a secret (e.g., `GH_PAT_RELEASES`) and passed to the release action's `token` input.
# 2. Release Pruning: GitHub Actions do not have a built-in way to easily prune old releases by count or age.
#    This would require custom scripting using the GitHub API (e.g., via `gh` CLI or a dedicated action).
#    For now, old releases will accumulate.
# 3. Error Handling: The JSON extraction is basic. If the Python script's output format changes,
#    the awk command might need adjustment. Consider more robust output handling from the Python script if needed.
# 4. Cron Schedule: '0 1 * * *' is 1 AM UTC. Adjust this to your preferred time.
#    See https://crontab.guru/ for help with cron expressions.
